using GMAPI.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace IpsenApiTesting
{
    public static class SeedData
    {
        /**
         * Data that gets generated by test things
         */
        public static void PopulateTestData(PostgresDatabaseContext dbContext) {
            dbContext.Accounts.Add(new Account
            {
                Email = "oetze@live.nl",
                FirstName = "Oetze",
                MiddleName = "van den",
                LastName = "Broek"
            });
        }

    }
}
